[package]
name = "slow-read"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
async-io = "1.12"
async-fs = "1.6"
executor = "0.8"
